[[main]]
name = "Introduction"
identifier = "intro"
weight = 100
url = "/"

[[main]]
name = "More About Me"
identifier = "about-me"
weight = 200

[[main]]
name = "My Skills"
identifier = "skills"
weight = 210
parent = "about-me"
url = "/skills/"

[[main]]
name = "My Tools"
identifier = "mytools"
weight = 220
parent = "about-me"
url = "/mytools/"

[[main]]
name = "Portfolio"
identifier = "portfolio"
weight = 300
url = "/portfolio/"

# [[main]]
# name = "Services"
# identifier = "services"
# weight = 400
# url = "/services/"

[[main]]
name = "Blog"
identifier = "blog"
weight = 500
url = "/blog/"

[[main]]
name = "Links"
identifier = "links"
weight = 600
url = "/links/"
