title = "MothWaves"
author = "MothWaves"
profilePicture = "images/profile.jpg"
description = """
Artist and Developer
Open for Work!
"""
favicon = "favicons/"
#Alternative Descriptions:
# "Artist and Developer"
# "Professional Insect"

# Itch.io account
[[socialIcons]]
icon = "fab fa-itch-io"
title = "Itch.Io"
url = "https://mothwaves.itch.io"

# Github Account
[[socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/MothWaves"

# Mastodon Account
[[socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://mastodon.gamedev.place/@MothWaves"

# Instagram account
[[socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/waves.in.dreams"

# Ko-fi account
[[socialIcons]]
icon = "fas fa-hand-holding-heart"
title = "Ko-Fi"
url = "https://ko-fi.com/mothwaves"

# Matrix account
[[socialIcons]]
icon = "fas fa-comment-dots"
title = "Matrix Messaging"
url = "https://matrix.to/#/@mothwaves:matrix.org"

# GPG Keys
[[socialIcons]]
icon = "fas fa-key"
title = "GPG"
url = "https://mothwaves.github.io/.well-known/gpg.txt"

# Email
[[socialIcons]]
icon = "fas fa-envelope"
title = "Work Email"
url = "mailto:mothwaves.work@outlook.com"


