title = "MothWaves"
author = "MothWaves"
profilePicture = "images/profile.jpg"
description = """
Artist and Developer
Open for Work!
"""
favicon = "favicons/"
#Alternative Descriptions:
# "Artist and Developer"
# "Professional Insect"

# Mastodon Account
[[socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://mastodon.gamedev.place/@MothWaves"

# Instagram account
[[socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/waves.in.dreams"

# Github Account
[[socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/MothWaves"

# Itch.io account
[[socialIcons]]
icon = "fab fa-itch-io"
title = "Itch.Io"
url = "https://mothwaves.itch.io"

# GPG Keys
[[socialIcons]]
icon = "fas fa-key"
title = "GPG"
url = ".well-known/gpg.txt"

# Email
[[socialIcons]]
icon = "fas fa-envelope"
title = "Mastodon"
url = "https://mastodon.gamedev.place/@MothWaves"

# Ko-fi account
[[socialIcons]]
icon = "fas fa-hand-holding-heart"
title = "Ko-Fi"
url = "https://ko-fi.com/mothwaves"
